package com.gateway.auth.model;

public enum AuditAction {
    REGISTER,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT,
    EMAIL_VERIFICATION_SENT,
    EMAIL_VERIFIED,
    EMAIL_VERIFICATION_FAILED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_SUCCESS,
    PASSWORD_RESET_FAILED,
    TOKEN_REFRESHED,
    ACCOUNT_LOCKED,
    OTP_RESENT,
    RATE_LIMIT_EXCEEDED
}
